services:
  nginx:
    build:
      context: .
      dockerfile: web.Dockerfile
    container_name: server
    ports:
      - "80:80"
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: fp_api
    ports:
      - "3000:3000"
