services:
  fp_dev_db:
    image: postgres:17.0
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass1234
    volumes:
      - db:/var/lib/postgresql/data
  event-store:
    image: mongo:6.0.4
    ports:
      - "27018:27017"
    environment:
      - MONGODB_DATABASE="vf-event-store"
    command: mongod --replSet vf-event-store-repl-set
    volumes:
      - ./scripts/event-store-mongoinit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
volumes:
  db:
    driver: local
