services:
  nginx:
    build:
      context: .
      dockerfile: web.Dockerfile
    container_name: server
    depends_on:
      - fp_db
      - api
      - keycloak
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: fp_api
    depends_on:
      - fp_db
    ports:
      - "3000:3000"
    env_file:
      - .env
  fp_db:
    image: postgres:17.0
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    container_name: keycloak
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME
      - KC_BOOTSTRAP_ADMIN_PASSWORD
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_PROXY_HEADERS=xforwarded
    command: start-dev
    volumes:
      - ./keycloak/data:/opt/keycloak/data
      - ./keycloak-config:/opt/keycloak/conf
volumes:
  db:
    driver: local
